version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.15.2
    steps:
      - checkout
      - run: npm ci
      - run:
          name: "serve app"
          command: npm start
          background: true
      - run:
          name: "run cypress"
          command: npm test
      - store_test_results:
          path: results

workflows:
  build-and-test:
    jobs:
      - build-and-test
