version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install http-server cypress
            - run:
                name: "serve app"
                command: npm start
                background: true
            - run:
                name: "run cypress"
                command: npm test
            - store_test_results:
                path: results

workflows:
    build-and-test:
      jobs:
        - build-and-test