version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cypress/base:10.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: "serve app"
          command: npm start
          background: true
      - run:
          name: "run cypress"
          command: npm test
      - store_test_results:
          path: results

workflows:
  build-and-test:
    jobs:
      - build-and-test
