version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.1

workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm start'
          post-steps:
            - store_test_results:
                path: results
